parameters:
#    oradt_batch.example.class: Oradt\BatchBundle\Example

services:
#    oradt_batch.example:
#        class: %oradt_batch.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
