parameters:
#    oradt_common.example.class: Oradt\CommonBundle\Example

services:
#    oradt_common.example:
#        class: %oradt_common.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
